--PART A
CREATE TABLE STUDENT_INFO(

RNO INT,
NAME VARCHAR(50),
BRANCH VARCHAR(50),
SPI DECIMAL(8,2),
BKLOG INT


)
DROP TABLE STUDENT_INFO


INSERT INTO STUDENT_INFO VALUES
(101,'RAJU','CE',8.80,0),
(102,'AMIT','CE',2.20,3),
(103,'SANJAY','ME',1.50,6),
(104,'NEHA','EC',7.65,1),
(105,'MERA','EE',5.52,2),
(106,'MAHESH','EC',4.50,0)



CREATE VIEW PERSONAL AS SELECT *FROM STUDENT_INFO
SELECT *FROM PERSONAL

CREATE VIEW ACADEMICDATA AS SELECT RNO,NAME,BRANCH FROM STUDENT_INFO
SELECT *FROM ACADEMICDATA

CREATE VIEW STUDENT_BKLOG AS SELECT *FROM STUDENT_INFO
SELECT *FROM STUDENT_BKLOG

CREATE VIEW STUDENT_PATTERN AS SELECT RNO,NAME,BRANCH FROM STUDENT_INFO
WHERE NAME LIKE '____'
SELECT *FROM STUDENT_PATTERN

INSERT INTO ACADEMICDATA VALUES(107,'MEET','ME')
SELECT *FROM ACADEMICDATA

CREATE VIEW STUDENT_DETAILS AS SELECT *FROM STUDENT_INFO

UPDATE STUDENT_DETAILS SET BRANCH='ME' WHERE NAME='AMIT'
SELECT*FROM STUDENT_DETAILS


DELETE ACADEMICDATA WHERE RNO=104
SELECT *FROM ACADEMICDATA


--PART B

CREATE VIEW SPIABOVE AS SELECT *FROM STUDENT_INFO 
WHERE SPI>8.5
SELECT *FROM SPIABOVE

CREATE VIEW NOBACK AS SELECT *FROM STUDENT_INFO WHERE BKLOG=0
SELECT *FROM NOBACK

CREATE VIEW COMPUTERVIEW AS SELECT *FROM STUDENT_INFO 
WHERE BRANCH='CE'
SELECT *FROM COMPUTERVIEW


--PART C

CREATE VIEW RESULT_EC AS SELECT NAME,SPI FROM STUDENT_INFO 
WHERE SPI<5 AND BRANCH='EC'
SELECT*FROM RESULT_EC

UPDATE RESULT_EC SET SPI=4.90 WHERE NAME='MAHESH'
SELECT *FROM RESULT_EC

CREATE VIEW STU_BKLOG AS SELECT RNO,NAME,BKLOG FROM STUDENT_INFO
WHERE NAME LIKE 'M%' AND BKLOG>5
SELECT *FROM STU_BKLOG

DROP VIEW COMPUTERVIEW








